services:
  server:
    image: novadityap/real-estate-app-server-dev
    container_name: real-estate-app-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.development
    env_file:
      - ./server/.env.development
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always
    networks:
      - real-estate-app-dev

  client:
    image: novadityap/real-estate-app-client-dev
    container_name: real-estate-app-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.development
    env_file:
      - ./client/.env.development
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - real-estate-app-dev

  postgres:
    container_name: real-estate-app-postgres-dev
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: aditya123
      POSTGRES_DB: real_estate_app
    networks:
      - real-estate-app-dev

volumes:
  postgres-data:
    name: postgres-data
networks:
  real-estate-app-dev:
    name: real-estate-app-dev
