services:
  server:
    image: novadityap/real-estate-app-server
    build:
      context: ./server
      dockerfile: Dockerfile.production
    ports:
      - "4000:4000"
    restart: always

  client:
    image: novadityap/real-estate-app-client
    build:
      context: ./client
      dockerfile: Dockerfile.production
    ports:
      - "3000:80"
    restart: always

