FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

COPY .env.production .env

RUN npx prisma generate

EXPOSE 4000

CMD ["sh", "-c", "npx prisma generate && npm run seed && npm start"]

